services:
  plex-mal-sync:
    image: ghcr.io/niklas2233/plex-mal-sync:latest
    container_name: plex-mal-sync
    ports:
      - "5057:5057"
    volumes:
      - ./plex_mal_sync_data:/data
    restart: unless-stopped
